site_name: retryhttp
site_description: Retry commonly transient HTTP errors.
site_url: https://github.com/austind/retryhttp

theme:
  name: "material"
  icon:
    logo: "material/school"
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: "red"
      accent: "red"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: "red"
      accent: "red"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_name: austind/retryhttp
repo_url: https://github.com/austind/retryhttp
edit_uri: ""

nav:
  - Introduction: "index.md"
  - User Guide: "guide.md"
  - API Reference: "api.md"

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
