name: CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Nox
        uses: wntrblm/nox@2024.04.15
        with:
          python-versions: "3.8, 3.9, 3.10, 3.11, 3.12"

      - name: Run Nox
        run: nox -t test
      